apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment
  namespace: portal
  labels:
    app: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal-container
          image: zerohertzkr/server-portal:v1.4.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: portal-service
  namespace: portal
spec:
  selector:
    app: portal
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portal
  namespace: portal
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`zerohertz.xyz`)
      kind: Rule
      services:
        - name: portal-service
          port: 3000
  tls:
    certResolver: zerohertz-resolver
