name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Build')
    outputs:
      TAG: ${{ steps.extract_tag.outputs.TAG }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract tag from commit message
        id: extract_tag
        run: |
          TAG=$(echo "${{ github.event.head_commit.message }}" | grep -oP 'Build: \s*\K[\w\.]+')
          echo "Extracted tag is $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.directory }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/server-portal:latest,
            ${{ secrets.DOCKER_USERNAME }}/server-portal:${{ env.TAG }},
            ghcr.io/${{ secrets.GH_USERNAME }}/server-portal:latest,
            ghcr.io/${{ secrets.GH_USERNAME }}/server-portal:${{ env.TAG }}

      - name: Slack webhook
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: server-portal
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_CHECK }}
        if: always()

  push:
    name: Push Manifest
    needs: build
    runs-on: ubuntu-latest
    env:
      TAG: ${{ needs.build.outputs.TAG }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Change manifest
        run: sed -i "s|zerohertzkr/server-portal:[^ ]*|zerohertzkr/server-portal:${{ env.TAG }}|" k8s/main.yaml

      - name: git push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config credential.helper store
          git add k8s/main.yaml
          git commit -m ":tada: Update: Image [${{ env.TAG }}]"
          git push

      - name: Slack webhook
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: server-portal
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_CHECK }}
        if: always()
